---
# tasks file for worker
- name: Add Worker to Swarm
  docker_swarm:
    state: join
    join_token: "{{ hostvars['ansible-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'ansible-manager:2377' ]